name: Build Plugin

on:
  push:
    branches:
      - master
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  upload_asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-distribution-sha-256-sum-warning: false
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          cache: gradle
          java-version: 21
      - run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      # upload the jar to the action as a build artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Plugin Jar Files'
          path: build/libs/*.jar